### ISSUE TITLE
There no mobs on my Sub Server

### ISSUE THREAD

**Issue by vnZ-Network** [samik3k/mu_online_lgnd#7]
Hi ! Thx you for ur great work, but i have few problem trying to create a sub with mobs ~ NPC
INSERT INTO mu_online_game.monster
SELECT `your_new_server_id`, `id`, `type`, `name`, `world`, `x1`, `y1`, `x2`, `y2`, `direction`, `spawn_delay`, `spawn_distance`,
`respawn_time_min`, `respawn_time_max`, `respawn_id`, `move_distance`, `npc_function`, `item_bag`, `script_name`, `elemental_attribute`, `disabled`, `quantity`
FROM mu_online_game.monster WHERE 1 AND your_awesome_where_expression;

WHERE 1 AND "";
i dont get what you on this line

**Comment by samik3k** [comment]
Did you found right answer?

your_awesome_where_expression change to anything, type = 2 or world = 19, whatever
